// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: get_user_posts.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const userPosts = `-- name: UserPosts :many
select p.id, p.created_at, p.updated_at, published_at, url, title, description, p.feed_id, ff.id, ff.created_at, ff.updated_at, user_id, ff.feed_id from posts p
join feed_follows ff
on p.feed_id = ff.feed_id and  ff.user_id = $1
order by published_at desc
limit $2
`

type UserPostsParams struct {
	UserID uuid.UUID
	Limit  int32
}

type UserPostsRow struct {
	ID          uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
	PublishedAt time.Time
	Url         string
	Title       string
	Description string
	FeedID      uuid.UUID
	ID_2        uuid.UUID
	CreatedAt_2 time.Time
	UpdatedAt_2 time.Time
	UserID      uuid.UUID
	FeedID_2    uuid.UUID
}

func (q *Queries) UserPosts(ctx context.Context, arg UserPostsParams) ([]UserPostsRow, error) {
	rows, err := q.db.QueryContext(ctx, userPosts, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserPostsRow
	for rows.Next() {
		var i UserPostsRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PublishedAt,
			&i.Url,
			&i.Title,
			&i.Description,
			&i.FeedID,
			&i.ID_2,
			&i.CreatedAt_2,
			&i.UpdatedAt_2,
			&i.UserID,
			&i.FeedID_2,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
