// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: get_post.sql

package database

import (
	"context"
	"time"
)

const getPost = `-- name: GetPost :one
select id, created_at, updated_at, published_at, url, title, description, feed_id from Posts
where published_at = $1
and url = $2
and title = $3
`

type GetPostParams struct {
	PublishedAt time.Time
	Url         string
	Title       string
}

func (q *Queries) GetPost(ctx context.Context, arg GetPostParams) (Post, error) {
	row := q.db.QueryRowContext(ctx, getPost, arg.PublishedAt, arg.Url, arg.Title)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublishedAt,
		&i.Url,
		&i.Title,
		&i.Description,
		&i.FeedID,
	)
	return i, err
}
