// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: get_users_feeds.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getUsersFeeds = `-- name: GetUsersFeeds :many
select id, created_at, updated_at, name, url, last_fetched_at from feeds
where feeds.id in
(
    select ff.feed_id from feed_follows ff
    where ff.user_id = $1
)
`

func (q *Queries) GetUsersFeeds(ctx context.Context, userID uuid.UUID) ([]Feed, error) {
	rows, err := q.db.QueryContext(ctx, getUsersFeeds, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Feed
	for rows.Next() {
		var i Feed
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Name,
			&i.Url,
			&i.LastFetchedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
